export default {
  GET_ALL_USERS_SUCCESS: "Get all users successfully!",
  GET_USER_SUCCESS: "Get users successfully!",
  LOGIN_SUCCESS: "Login successfully!",
  LOGOUT_SUCCESS: "Logout successfully!",
  REGISTER_SUCCESS: "Register successfully!",
  VERIFY_EMAIL_SUCCESS: "Email verified successfully!",
  FORGOT_PASSWORD_SUCCESS: "Password reset instructions sent to your email!",
  RESET_PASSWORD_SUCCESS: "Password updated successfully!",
  CHANGE_PASSWORD_SUCCESS: "Change password successfully!",
  VIEW_PROFILE_SUCCESS: "View profile successfully!",
  UPDATE_PROFILE_SUCCESS: "Update profile successfully!",
  UPDATE_ROLE_SUCCESS: "Update role successfully!",
  UPDATE_STATUS_SUCCESS: "Update status successfully!",
  UPDATE_BLOCK_SUCCESS: "Update block successfully!",
  REFRESH_ACCESS_TOKEN_SUCCESS: "Refresh access token successfully!",
  PRODUCT_RETRIVED: "Products retrieved successfully",
  GET_ALL_PRODUCTS_SUCCESS: "Get all products successfully",
  GET_PRODUCT_BY_ID_SUCCESS: "Get product by id successfully ",
  GET_ALL_CATEGORY_SUCCESS: "Get all categories successfully",
  GET_CATEGORY_BY_ID_SUCCESS: "Get category by successfully",
  CREATE_CATEGORY_SUCCESS: "Create category successfully",
  DELETE_USER_SUCCESS: "Delete user successfully",
};
